from subprocess import call
import glob

testEnv = Environment(CCFLAGS=['/EHsc', '/D_WINDLL'], LINKFLAGS=['/subsystem:console'], CPPPATH=['../include/boost/include/boost-1_66', '../src/'], LIBPATH='../include/boost/lib/')

src_files = glob.glob('../src/*.cpp') + glob.glob('../tests/*.cpp')
src_files.remove('../src\\main.cpp')
name = 'test'
target2 = testEnv.Program(name, src_files)
